name: 'Terraform ApiGw Deploy'
on:
  push:
    branches:
      - main
    paths:
      - 'main.tf' 
      - '.github/workflows/gke-apigw-deploy.yml'
env:
  TF_ROOT: './'
  TF_FILE: 'main.tf'
  TERRAFORM_VERSION: '1.7.0'
jobs:
  terraform:
    name: 'Terraform Infrastructe'
    runs-on: ubuntu-latest
    environment: development 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_ROOT }}
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.TF_ROOT }}
      # - name: Terraform Unlock Plan
      #   id: unlock
      #   run: terraform force-unlock 1763560149459078 -auto-approve
      #   working-directory: ${{ env.TF_ROOT }}
      - name: Terraform Move Plan
        id: move
        run: terraform state mv 'google_container_cluster.autopilot_cluster' 'google_container_cluster.standard_cluster'
        working-directory: ${{ env.TF_ROOT }}
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=tfplan -var "gcp_project=${{ secrets.GCP_PROJECT_ID }}"
        working-directory: ${{ env.TF_ROOT }}
        continue-on-error: true
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_ROOT }}
        